saveExact: true
minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - vite@7.3.5
  - '@babel/core@7.29.1'
  - piscina@5.1.5

overrides:
  vite: ">=7.3.5"
  piscina: ">=5.1.5"
  esbuild: ">=0.28.1"
  "@babel/core": ">=7.29.1"

allowBuilds:
  esbuild: true
